title: "Benjie K"
description: "Portfolio & Blog for Benjie Kibblewhite: Web Developer"
about: "Benjie is a Front-End Developer. He's good friends with JavaScript, React, React Native, Vue, and the core languages that make the web work: HTML and CSS."
location: "Toronto, Canada"
email: benjie@benjie.ca
baseurl: ""

url: "https://benjie.ca" # replace by your site's url
twitter_username: kibben
github_username:  ostaron
linkedin_username: benjie-k
author: "Benjie Kibblewhite"


defaults:
  - scope:
      path: "images"
    values:
      image: true

# google analytics tracking code, please change the value
g_analytics: "UA-114608619-1"

# add your disqus to enable comments
disqus_shortname:

# add your disqus to enable comments
disqus_shortname:

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
about_btn: "About"
imprint_btn: "Imprint"
name_badge: "by"
rss_badge: "Subscribe to the feed!"

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4

# third party gems
gems:

whitelist:

# exclude files
exclude:
  - LICENSE
  - README.md
  - .c9
